import type { Types } from 'types/index';

import { NIL, NWL, WSP } from 'chars';
import { cc as ch } from 'lexical/codes';
import { Action } from 'lexical/enum';
import { parse } from 'parse/parser';
import { is, isLast, isUndefined, not } from 'utils/helpers';
import { object } from 'utils/native';

export function json () {

  /**
   * Reference to `rules.parsed` which is the  already parsed record generated by the lexer.
   */
  const { data, rules } = parse;

  /** External indexes */
  const exidx = object(null);

  /**  Holds reference to the source ending index or the token ending index. */
  const b = parse.ender < 1 || parse.ender > data.token.length ? data.token.length : parse.ender + 1;

  /** The current level */
  const levels = parse.start > 0 ? Array(parse.start).fill(0, 0, parse.start) : [];

  /** Stores comma status of current block */
  const commaWithin: boolean[] = [];

  /** Used to identify ternary statments */
  const ternary: number[] = [];

  /** Stores token indexes where extra indentation occurs from ternaries and broken method chains */
  const extraIndent = [ [] ];

  /** Array where a method break has occurred */
  const arrayBreaks: boolean[] = [];

  /** Attempt to identify object destructuring */
  const destruct: boolean[] = [];

  /** Counts items in destructured lists */
  const itemsCounts: number[] = [];

  /**  Are you in a list right now? */
  const wordListing = [];
  const count = [];

  /* -------------------------------------------- */
  /* LOCAL SCOPES                                 */
  /* -------------------------------------------- */

  /** Holds the current index position. */
  let a: number = parse.start;

  /** The indentation level as per `indentLevel` which is an internal reference. */
  let indent: number = rules.indentLevel;

  /** Remembers the list status of the most recently closed block */
  let lastlist: boolean = false;

  /** Stands for "current type" */
  let ctype: Types = NIL; // ctype stands for "current type"

  /** Stands for "current token" */
  let ctoke: string = NIL;

  /** Stands for "last type" */
  let ltype: Types = data.types[0]; // ltype stands for "last type"

  /** Stands for "last token" */
  let ltoke: string = data.token[0];

  /** Within String */
  let instr = 0;

  function Comments () {

    Destruct(false, false);

    const ind = rules.commentIndent === true ? indent : 0;

    if (data.types[a - 1] === 'comment' || data.types[a + 1] === 'comment') {

      levels[a - 1] = ind;

    } else if (data.lines[a] < 2) {

      let aa = a + 1;

      if (data.types[aa] === 'comment') {
        do aa = aa + 1;
        while (aa < b && data.types[aa] === 'comment');
      }

      levels[a - 1] = -10;

      levels.push(indent);

      if (rules.commentIndent === true && levels[a] > -1 && data.lines[a] < 3) {
        data.lines[a] = 3;
      }

      return;

    } else if (is(data.token[a - 1], ch.COM)) {

      levels[a - 1] = ind;

    } else if (is(ltoke, ch.LCB) && data.types[a - 1] !== 'comment' && data.lines[0] < 2) {

      levels[a - 1] = /\n/.test(ctoke) ? ind : -10;

    } else {

      levels[a - 1] = ind;

    }

    levels.push(indent);

    if (levels[a] > -1 && data.lines[a] < 3) {

      // HOT PATCH
      //
      // When comment lines follow comment lines we don't
      // want indentation between them, this fixes that.
      //
      if (data.types[a - 1] === 'comment' && ctoke.startsWith('//')) {
        data.lines[a] = 2;
      } else {
        data.lines[a] = 3;
      }

    }

  };

  function Destruct (listFix: boolean, override: boolean) {

    // listfix  - at the end of a list correct the containing list override - to
    // break arrays with more than 4 items into a vertical list
    let c = a - 1;
    let d = (listFix === true) ? 0 : 1;

    const ei = (extraIndent[extraIndent.length - 1] === undefined)
      ? []
      : extraIndent[extraIndent.length - 1];

    const arrayCheck = (
      override === false &&
      data.stack[a] === 'array' &&
      listFix === true &&
      not(ctoke, ch.LSB)
    );

    if (
      destruct[destruct.length - 1] === false || (
        data.stack[a] === 'array' &&
        rules.arrayFormat === 'inline'
      ) || (
        data.stack[a] === 'object' &&
        rules.objectIndent === 'inline'
      )
    ) {
      return;
    }

    destruct[destruct.length - 1] = false;

    do {
      if (data.types[c] === 'end') {
        d = d + 1;
      } else if (data.types[c] === 'start') {
        d = d - 1;
      }

      if (data.stack[c] === 'global') break;

      if (d === 0) {

        if (
          data.stack[a] === 'class' ||
          data.stack[a] === 'map' || (
            arrayCheck === false && (
              (
                listFix === false &&
                data.token[c] !== '(' &&
                data.token[c] !== 'x('
              ) || (
                listFix === true &&
                is(data.token[c], ch.COM)
              )
            )
          )
        ) {

          if (data.types[c + 1] === 'liquid_start') {

            if (data.lines[c] < 1) {
              levels[c] = -20;
            } else {
              levels[c] = indent - 1;
            }

          } else if (ei.length > 0 && ei[ei.length - 1] > -1) {
            levels[c] = indent - 1;
          } else {
            levels[c] = indent;
          }

        } else if (data.stack[a] === 'array' && data.types[a] === 'operator') {

          if (is(data.token[c], ch.COM)) levels[c] = indent;
          if (c === data.begin[a]) break;

        }

        if (listFix === false) break;

      }

      if (d < 0) {

        if (
          data.types[c + 1] === 'liquid_start' ||
          data.types[c + 1] === 'template_string_start'
        ) {

          if (data.lines[c] < 1) {
            levels[c] = -20;
          } else {
            levels[c] = indent - 1;
          }

          levels[c] = -20;

        } else if (ei.length > 0 && ei[ei.length - 1] > -1) {
          levels[c] = indent - 1;
        } else {
          levels[c] = indent;
        }
        break;
      }

      c = c - 1;

    } while (c > -1);

  };

  function Start () {

    const deep = data.stack[a + 1];

    const deeper = a === 0 ? data.stack[a] : data.stack[a - 1];

    commaWithin.push(false);
    extraIndent.push([]);
    arrayBreaks.push(false);
    wordListing.push(false);
    itemsCounts.push(0);

    if (
      is(ctoke, ch.LCB) &&
        deep === 'object' &&
        ltype !== 'operator' &&
        ltype !== 'start' &&
        ltype !== 'string' &&
        ltype !== 'number' &&
        deeper !== 'object' &&
        deeper !== 'array' &&
        a > 0
    ) {

      // curly brace not in a list and not assigned
      destruct.push(true);
    } else {

      // not destructured (multiline)
      destruct.push(false);
    }

    indent = indent + 1;

    if (is(ctoke, ch.LCB)) {

      if (data.types[a - 1] !== 'comment') {

        if (ltype === 'markup') {

          levels[a - 1] = indent;

        } else if (
          is(ltoke, ch.LCB) ||
          is(ltoke, ch.LSB) ||
          is(ltoke, ch.RCB)
        ) {

          levels[a - 1] = indent - 1;
        }
      }

      if (deep === 'object') {

        if (rules.objectIndent === 'indent') {
          destruct[destruct.length - 1] = false;
          levels.push(indent);
          return;
        }

        if (rules.objectIndent === 'inline') {
          destruct[destruct.length - 1] = true;
          levels.push(-20);
          return;
        }
      }

      if (destruct[destruct.length - 1] === true) {
        if (ltype !== 'word' && ltype !== 'reference') {
          levels.push(-20);
          return;
        }
      }

      levels.push(indent);

      return;
    }

    if (is(ctoke, ch.LSB)) {

      if (is(ltoke, ch.LSB)) commaWithin[commaWithin.length - 2] = true;

      if (
        data.types[a - 1] !== 'comment' && (
          ltype === 'end' ||
          ltype === 'word' ||
          ltype === 'reference'
        )
      ) {

        levels[a - 1] = -20;

      } else if (
        is(ltoke, ch.LSB) ||
        is(ltoke, ch.LCB) ||
        ltoke === 'x{') {

        levels[a - 1] = indent - 1;

      }

      if (data.stack[a] === 'attribute') {
        levels.push(-20);
        return;
      }

      if (rules.arrayFormat === 'indent') {
        destruct[destruct.length - 1] = false;
        levels.push(indent);
        return;
      }

      if (rules.arrayFormat === 'inline') {
        destruct[destruct.length - 1] = true;
        levels.push(-20);
        return;
      }

      if (destruct[destruct.length - 1] === true) {
        if (data.types[a + 1] === 'liquid_start') {
          indent = indent + 1;
          levels.push(indent);
        } else {
          levels.push(-20);
        }

        return;

      }

      let c = a + 1;

      do {

        if (is(data.token[c], ch.RSB)) {
          levels.push(-20);
          return;
        }

        if (is(data.token[c], ch.COM)) {
          levels.push(indent);
          return;
        }

        c = c + 1;

      } while (c < b);

      levels.push(-20);

    }
  };

  function Ender () {

    /**
     * Extra Indentations
     */
    const ei = isUndefined(extraIndent[extraIndent.length - 1]) ? [] : extraIndent[extraIndent.length - 1];

    function markuplist () {

      let aa = a;
      let markup = false;
      const begin = data.begin[aa];

      do {

        aa = aa - 1;

        if (data.lexer[aa] === 'markup') {
          markup = true;
          break;
        }

        if (data.begin[aa] !== begin) aa = data.begin[aa];

      } while (aa > begin);

      if (markup === true) {

        aa = a;

        do {
          aa = aa - 1;
          if (data.begin[aa] !== begin) {
            aa = data.begin[aa];
          } else if (is(data.token[aa], ch.COM)) {
            levels[aa] = indent + 1;
          }
        } while (aa > begin);

        levels[begin] = indent + 1;
        levels[a - 1] = indent;

      } else {
        levels[a - 1] = -20;
      }
    };

    if (is(data.token[a + 1], ch.COL) && (
      data.stack[a] === 'object' ||
      data.stack[a] === 'array'
    )) {

      Destruct(true, false);

    }

    if (is(data.token[data.begin[a] - 1], ch.COM) && (
      is(data.token[a + 1], ch.RCB) ||
      is(data.token[a + 1], ch.RSB)
    ) && (
      data.stack[a] === 'object' ||
      data.stack[a] === 'array'
    )) {

      Destruct(true, false);

    }

    indent = indent - 1;

    if (
      rules.bracePadding === false &&
      ctoke !== '}' &&
      ctoke !== ']' &&
      ltype !== 'markup' &&
      ltype !== 'liquid') {

      levels[a - 1] = -20;

    }

    if (
      rules.bracePadding === true &&
      ltype !== 'start' &&
      ltoke !== ';' &&
      (
        levels[data.begin[a]] < -9 ||
        destruct[destruct.length - 1] === true
      )
    ) {

      levels[data.begin[a]] = -10;
      levels[a - 1] = -10;
      levels.push(-20);

    } else if (
      data.stack[a] === 'array' && (
        ei.length > 0 ||
        arrayBreaks[arrayBreaks.length - 1] === true
      )
    ) {

      ExtraIndent();

      destruct[destruct.length - 1] = false;
      levels[data.begin[a]] = indent + 1;
      levels[a - 1] = indent;
      levels.push(-20);

    } else if (ei.length > 0 && (
      data.stack[a] === 'object' || (
        data.begin[a] === 0 &&
        is(ctoke, ch.RCB)
      )
    )) {

      ExtraIndent();

      destruct[destruct.length - 1] = false;
      levels[data.begin[a]] = indent + 1;
      levels[a - 1] = indent;
      levels.push(-20);

    } else if (destruct[destruct.length - 1] === true) {

      if (
        is(ctoke, ch.RSB) &&
        data.begin[a] - 1 > 0 &&
        data.token[data.begin[data.begin[a] - 1]] === '['
      ) {
        destruct[destruct.length - 2] = false;
      }

      if (data.begin[a] < levels.length) levels[data.begin[a]] = -20;

      if (parse.language === 'jsx' || parse.language === 'tsx') {
        markuplist();
      } else if (is(ctoke, ch.RSB) && levels[data.begin[a]] > -1) {
        levels[a - 1] = levels[data.begin[a]] - 1;
      } else {
        levels[a - 1] = -20;
      }

      levels.push(-20);

    } else if (
      data.types[a - 1] === 'comment' &&
      data.token[a - 1].substring(0, 2) === '//'
    ) {

      if (data.token[a - 2] === 'x}') levels[a - 3] = indent + 1;

      levels[a - 1] = indent;
      levels.push(-20);

    } else if (
      ltype.indexOf('liquid') < 0 && // PATCH SO LIQUID TOKENS DONT END WITH: }}} (3 LCB)
      data.types[a - 1] !== 'comment' && (
        (
          is(ltoke, ch.LCB) &&
          is(ctoke, ch.RCB)
        ) || (
          is(ltoke, ch.LSB) &&
          is(ctoke, ch.RSB)
        )
      )
    ) {

      levels[a - 1] = -20;
      levels.push(-20);

    } else if (is(ctoke, ch.RSB)) {

      if (
        (
          commaWithin[commaWithin.length - 1] === true &&
          destruct[destruct.length - 1] === false &&
          rules.arrayFormat !== 'inline'
        ) || (
          is(ltoke, ch.RSB) &&
          levels[a - 2] === indent + 1
        )
      ) {

        levels[a - 1] = indent;
        levels[data.begin[a]] = indent + 1;

      } else if (levels[a - 1] === -10) {

        levels[a - 1] = -20;
      }

      if (commaWithin[commaWithin.length - 1] === false) {

        if (is(ltoke, ch.RCB) || ltoke === 'x}') levels[a - 1] = indent;

        let c = a - 1;
        let d = 1;

        do {

          if (is(data.token[c], ch.RSB)) d = d + 1;
          if (is(data.token[c], ch.LSB)) {

            d = d - 1;

            if (d === 0) {

              if (
                c > 0 && (
                  is(data.token[c + 1], ch.LCB) ||
                  is(data.token[c + 1], ch.LSB) ||
                  data.token[c + 1] === 'x{'
                )
              ) {

                levels[c] = indent + 1;

                break;
              }

              if (not(data.token[c + 1], ch.LSB) || lastlist === false) {
                levels[c] = -20;
                break;
              }

              break;
            }
          }

          if (d === 1 && data.token[c] === '+' && levels[c] > 1) {
            levels[c] = levels[c] - 1;
          }

          c = c - 1;

        } while (c > -1);

      }

      if (rules.arrayFormat === 'inline') {

        let c = a;
        const begin = data.begin[a];

        do {
          c = c - 1;
          if (data.types[c] === 'end') break;
        } while (c > begin);

        if (c > begin) {

          levels[data.begin[a]] = indent + 1;
          levels[a - 1] = indent;
        } else {
          levels[data.begin[a]] = -20;
          levels[a - 1] = -20;
        }

      } else if (levels[data.begin[a]] > -1) {

        levels[a - 1] = levels[data.begin[a]] - 1;

      }

      levels.push(-20);

    } else if (
      is(ctoke, ch.RCB) ||
      ctoke === 'x}' ||
      commaWithin[commaWithin.length - 1] === true
    ) {

      levels.push(indent);

      levels[a - 1] = indent;

    } else {

      levels.push(-20);

    }

    if (data.types[a - 1] === 'comment') levels[a - 1] = indent;

    ExtraIndent();

    lastlist = commaWithin[commaWithin.length - 1];

    commaWithin.pop();
    extraIndent.pop();
    arrayBreaks.pop();
    itemsCounts.pop();
    wordListing.pop();
    destruct.pop();

  };

  function ExtraIndent () {

    let c = 0;
    const ei = extraIndent[extraIndent.length - 1];

    if (ei === undefined) return;

    c = ei.length - 1;

    if (c < 0 || ei[c] < 0) return;

    if (is(ctoke, ch.COL)) {
      if (not(data.token[ei[c]], ch.QWS)) {
        do {
          ei.pop();
          c = c - 1;
          indent = indent - 1;
        } while (c > -1 && ei[c] > -1 && not(data.token[ei[c]], ch.QWS));
      }

      ei[c] = a;
      levels[a - 1] = indent;
    } else {

      do {
        ei.pop();
        c = c - 1;
        indent = indent - 1;
      } while (c > -1 && ei[c] > -1);
    }

    if ((data.stack[a] === 'array' || is(ctoke, ch.COM)) && ei.length < 1) {
      ei.push(-1);
    }
  };

  function External () {

    const skip = a;

    do {

      if (data.lexer[a + 1] === 'json' && data.begin[a + 1] < skip) break;
      if (data.types[a] === 'end' && data.begin[a] === skip) break;

      levels.push(0);

      a = a + 1;

    } while (a < b);

    // console.log(data.token[skip], data.types[skip], data.lexer[a]);
    exidx[skip] = a;
    levels.push(indent - 1);

  };

  function Operators () {

    const ei = isUndefined(extraIndent[extraIndent.length - 1]) ? [] : extraIndent[extraIndent.length - 1];

    if (
      ei.length > 0 &&
      ei[ei.length - 1] > -1 &&
      data.stack[a] === 'array'
    ) {

      arrayBreaks[arrayBreaks.length - 1] = true;
    }

    if (ctoke === ':') {

      if (data.stack[a] === 'object') {
        levels[a - 1] = -20;
      } else if (ternary.length > 0) {
        levels[a - 1] = indent;
      } else {
        levels[a - 1] = -10;
      }

      levels.push(-10);

    }

  };

  function Separators () {

    const ei = isUndefined(extraIndent[extraIndent.length - 1]) ? [] : extraIndent[extraIndent.length - 1];

    if (ctoke === ',') {

      if (data.stack[a] === 'array' && rules.arrayFormat === 'indent') {
        levels[a - 1] = -20;
        levels.push(indent);
        return;
      }

      if (data.stack[a] === 'array' && rules.arrayFormat === 'inline') {
        levels[a - 1] = -20;
        levels.push(-10);
        return;
      }

      if (data.stack[a] === 'object' && rules.objectIndent === 'indent') {
        levels[a - 1] = -20;
        levels.push(indent);
        return;
      }

      if (data.stack[a] === 'object' && rules.objectIndent === 'inline') {
        levels[a - 1] = -20;
        levels.push(-10);
        return;
      }

      if (ei.length > 0) {

        if (ei[ei.length - 1] > -1) ExtraIndent();

        levels[a - 1] = -20;
        levels.push(indent);
        return;
      }

      levels[a - 1] = -20;

      if (data.types[a + 1] !== 'end') {
        itemsCounts[itemsCounts.length - 1] = itemsCounts[itemsCounts.length - 1] + 1;
      }

      if (
        itemsCounts[itemsCounts.length - 1] > 3 && (
          data.stack[a] === 'array' ||
          data.stack[a] === 'object'
        )
      ) {

        if (destruct[destruct.length - 1] === true) Destruct(true, true);

        levels[a - 1] = -20;

        if (arrayBreaks[arrayBreaks.length - 1] === true) {
          levels.push(indent);
          return;
        }

        const begin = data.begin[a];
        let c = a;

        do {

          if (data.types[c] === 'end') {
            c = data.begin[c];
          } else {
            if (is(data.token[c], ch.COM) && data.types[c + 1] !== 'comment') {
              levels[c] = indent;
            }
          }

          c = c - 1;

        } while (c > begin);

        levels[begin] = indent;
        arrayBreaks[arrayBreaks.length - 1] = true;

        return;
      }

      if (data.stack[a] === 'object') {

        if (destruct[destruct.length - 1] === true && data.types[data.begin[a] - 1] !== 'word') {

          const bb = data.begin[a];
          let aa = a - 1;

          do {
            if (data.begin[aa] === bb) {

              if (is(data.token[aa], ch.COM)) break;
              if (is(data.token[aa], ch.COL)) {
                Destruct(true, false);
                break;
              }
            }

            aa = aa - 1;

          } while (aa > bb);
        }
      }

      if (
        destruct[destruct.length - 1] === false || (
          is(data.token[a - 2], ch.PLS) && (
            ltype === 'string' ||
            ltype === 'number'
          ) &&
          levels[a - 2] > 0 && (
            is(ltoke, ch.DQO) ||
            is(ltoke, ch.SQO)
          )
        )
      ) {

        levels.push(indent);
        return;
      }

      if (destruct[destruct.length - 1] === true && data.stack[a] !== 'object') {
        levels.push(-10);
        return;
      }

      if (
        itemsCounts[itemsCounts.length - 1] < 4 && (
          data.stack[a] === 'array' ||
          data.stack[a] === 'object'
        )
      ) {

        levels.push(-10);
        return;
      }

      levels.push(indent);
      return;
    }

    levels.push(-20);

  };

  function Strings () {

    if (instr === 0 && ltype === 'liquid_start' && (data.stack[a - 1] === 'object' || data.stack[a - 1] === 'array')) {
      levels[a - 1] = indent + 1;
    }

    if (ctoke.length === 1) {

      levels.push(-20);

      if (data.lines[a] === 0) levels[a - 1] = -20;

    } else if (ltype === 'liquid') {

      levels[a - 1] = -10;

    } else {

      levels.push(-10);

    }

    if (
      (
        is(ltoke, ch.COM) ||
        ltype === 'start'
      ) && (
        data.stack[a] === 'object' ||
        data.stack[a] === 'array'
      ) && (
        destruct[destruct.length - 1] === false && a > 0 &&
        ltype !== 'liquid_start'
      )
    ) {

      levels[a - 1] = indent;

    }

    if (instr > 0 && (isLast(ctoke, ch.DQO) || isLast(ctoke, ch.SQO))) --instr;

  };

  function Liquid () {

    // HOT PATCH
    //
    // Let's preserve occurances of Liquid tokens contained within
    // JSON strings. This prevents extra spaces being applied.
    //
    if (ctype === 'liquid_start') {

      if (ltype === 'string') {

        if (data.lines[a] > 1) {

          levels.push(indent);

        } else if (data.lines[a] === 1) {

          levels.push(-10);

        } else {

          levels.push(-20);

        }

      } else {

        if (data.lines[a] > 1) {

          levels.push(indent);

        } else if (data.lines[a] === 1) {

          levels.push(-10);

        } else {

          levels[a - 1] = -20;
          levels.push(-20);

        }

      }

    } else if (ctype === 'liquid_else') {

      if (data.lines[a] > 1) {

        levels[a - 1] = indent - 1;

        levels.push(indent);

      } else if (data.lines[a] === 1) {

        levels.push(-10);

      } else {

        levels.push(-20);

      }

    } else if (ctype === 'liquid_end') {

      if (ltype === 'liquid' && data.lines[a] < 2) {

        // TODO
        // We are enforcing inline on all tags, likely will produce
        // defect but will address this in the future.
        //
        levels.push(-10);

      } else {

        if (data.lines[a] > 1) {

          levels[a - 1] = indent;
          levels.push(indent);

        } else if (data.lines[a] === 0) {

          levels[a - 1] = -20;
          indent = indent - 1;
          levels.push(-20);

        } else {

          levels.push(-10);

        }
      }

    } else if (ctype === 'liquid') {

      if (is(ltoke, ch.COL) && levels[a - 2] === -10) levels[a - 2] = -20;

      if (data.lines[a] > 1) {

        levels.push(indent);

      } else if (data.lines[a] === 1) {

        levels.push(-10);

      } else {

        levels.push(-20);

      }
    }

  };

  function Words () {

    if (is(ltoke, ch.RSB)) levels[a - 1] = -10;

    // if (is(ltoke, ch.RCB) || ltoke === 'x}') levels[a - 1] = indent;

    if (rules.bracePadding === false && a < b - 1 && is(data.token[a + 1], ch.RCB)) {
      levels.push(-20);
      return;
    }

    if (
      data.types[a - 1] === 'comment' &&
      is(data.token[data.begin[a]], ch.LPR)
    ) {
      levels[a - 1] = indent + 1;
    }

    /* -------------------------------------------- */
    /* INLINE RETURNS LOGIC                         */
    /* -------------------------------------------- */

    levels.push(-10);

  };

  /**
   * Levels
   *
   * Sets the white space value between the current token and the next token
   *
   * - `-20` value means no white space
   * - `-10` means to separate with a space
   * - `0` and above is the number of indentation to insert
   */
  function Levels () {

    do {

      if (data.lexer[a] === 'json') {

        ctype = data.types[a];
        ctoke = data.token[a];

        if (ctype === 'comment') {
          Comments();
        } else if (ctype === 'string') {
          Strings();
        } else if (ctype === 'separator') {
          Separators();
        } else if (ctype === 'start') {
          Start();
        } else if (ctype === 'end') {
          Ender();
        } else if (ctype === 'operator') {
          Operators();
        } else if (ctype === 'word') {
          Words();
        } else if (ctype.indexOf('liquid') > -1) {
          Liquid();
        } else {
          levels.push(-10);
        }

        if (ctype !== 'comment') {
          ltype = ctype as any;
          ltoke = ctoke;
        }

        if (count.length > 0 && not(data.token[a], ch.RPR)) {

          if (data.types[a] === 'comment' && count[count.length - 1] > -1) {

            count[count.length - 1] = rules.wordWrap + 1;

          } else if (levels[a] > -1 || (is(data.token[a], ch.TQO) && data.token[a].indexOf(NWL) > 0)) {

            count[count.length - 1] = -1;

          } else if (count[count.length - 1] > -1) {

            count[count.length - 1] = count[count.length - 1] + data.token[a].length;

            if (levels[a] === -10) {
              count[count.length - 1] = count[count.length - 1] + 1;
            }
          }
        }

      } else {
        External();
      }

      a = a + 1;

    } while (a < b);

  }

  /**
   * Format Script
   *
   * Constructs the generated output result. The `output[]` array entries are joined
   * after traversal of the data~structure concludes.
   */
  function Format () {

    Levels();

    const output: string[] = [];
    const tab = rules.indentChar.repeat(rules.indentSize);
    const pres = rules.preserveLine + 1;

    let a = parse.start;

    let lastLevel = rules.indentLevel;

    function nl (tabs: number) {

      const total = (() => {

        if (a === b - 1) return 1;
        if (data.lines[a + 1] - 1 > pres) return pres;
        if (data.lines[a + 1] > 1) return data.lines[a + 1] - 1;

        return 1;

      })();

      return parse.crlf.repeat(total) + tab.repeat(tabs);

    };

    a = parse.start;

    do {

      if (data.lexer[a] === 'json') {

        output.push(data.token[a]);

        if (
          a < b - 1 &&
          data.lexer[a + 1] !== 'json' &&
          data.begin[a] === data.begin[a + 1] &&
          data.types[a + 1].indexOf('end') < 0 &&
          not(data.token[a], ch.COM)
        ) {

          output.push(WSP);

        } else if (levels[a] > -1) {

          if (parse.action === Action.Embed) {
            if (parse.ender !== a) {
              output.push(nl(levels[a]));
            }
          } else if (a !== b - 1) {

            output.push(nl(levels[a]));
          }

          lastLevel = levels[a];

        } else if (levels[a] === -10) {

          output.push(WSP);

          if (data.lexer[a + 1] !== 'json') lastLevel = lastLevel + 1;

        }
      } else {

        if (exidx[a] === a) {

          output.push(data.token[a]);

        } else {

          parse.ender = exidx[a];
          parse.start = a;

          output.push(parse.external(lastLevel));

          a = parse.iterator;

          if (levels[a] === -10) {
            output.push(WSP);
          } else if (levels[a] > -1) {
            output.push(nl(levels[a]));
          }

          // HOT PATCH
          // Reset indentation level, if not reset to 0 then
          // content will shift on save
          // ex.reset();

        }
      }

      a = a + 1;

    } while (a < b);

    parse.iterator = b - 1;

    // console.log(output);
    // console.log(data);
    return output.join(NIL);

  }

  return Format();

};
