import { Rules, ScriptRules } from 'types';

/**
 * Default Presets
 *
 * The default rules of Æsthetic from which all **presets** and
 * custom rules will be merged.
 */
export const defaults: Rules = {
  crlf: false,
  correct: false,
  preset: 'default',
  language: 'auto',
  endNewline: false,
  indentChar: ' ',
  indentLevel: 0,
  indentSize: 2,
  preserveLine: 2,
  wrap: 0,
  wrapFraction: 0,
  liquid: {
    allowPlebSyntactic: true,
    allowRubeSyntactic: true,
    argumentLineBreak: 0,
    commentIndent: true,
    commentPreserve: false,
    delimiterTrims: 'preserve',
    delimiterPlacement: 'preserve',
    equipoiseSpacing: true,
    filterLineBreak: 0,
    forceIndent: false,
    indentAttribute: false,
    lineBreakSeparator: 'before',
    lineBreakLogical: 'before',
    paddedTagList: [],
    dedentTagList: [],
    ignoreTagList: [],
    quoteConvert: 'none'
  },
  markup: {
    attributeCasing: 'preserve',
    attributeSort: false,
    attributeLineBreak: 3,
    attributePreserve: false,
    classListSort: false,
    classListUnique: false,
    commentDelimiter: 'preserve',
    commentIndent: true,
    commentPreserve: false,
    delimiterTerminus: false,
    forceIndent: false,
    forceInline: false,
    ignoreCSS: false,
    ignoreJS: true,
    ignoreJSON: false,
    preserveText: false,
    selfCloseSpace: true,
    selfCloseSVG: true,
    stripTextWrapLines: false,
    stripAttributeLines: false,
    quoteConvert: 'none',
    valueSpacing: 'preserve'
  },
  json: <ScriptRules>{
    arrayFormat: 'default',
    braceAllman: false,
    bracePadding: false,
    objectIndent: 'default',
    objectSort: false,

    braceStyle: 'none',
    caseSpace: false,
    commentIndent: false,
    commentNewline: false,
    correct: false,
    elseNewline: false,
    functionNameSpace: false,
    functionSpace: false,
    methodChain: 4,
    neverFlatten: false,
    noCaseIndent: false,
    preserveComment: false,
    styleGuide: 'none',
    ternaryLine: false,
    variableList: 'none',

    quoteConvert: 'double',
    endComma: 'never',
    noSemicolon: true,
    vertical: false
  },
  style: {
    commentIndent: false,
    commentNewline: false,
    atRuleSpace: true,
    classPadding: false,
    noLeadZero: false,
    preserveComment: false,
    sortSelectors: false,
    sortProperties: false,
    quoteConvert: 'none'
  },
  script: {
    arrayFormat: 'default',
    braceNewline: false,
    bracePadding: false,
    braceStyle: 'none',
    braceAllman: false,
    caseSpace: false,
    commentIndent: false,
    commentNewline: false,
    elseNewline: false,
    endComma: 'never',
    functionNameSpace: false,
    functionSpace: false,
    inlineReturn: true,
    methodChain: 4,
    neverFlatten: false,
    noCaseIndent: false,
    noSemicolon: false,
    objectSort: false,
    objectIndent: 'default',
    preserveComment: false,
    quoteConvert: 'none',
    styleGuide: 'none',
    ternaryLine: false,
    variableList: 'none',
    vertical: false
  }
};
