[build]
  command = "pnpm run build"

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "public"
    exclude  = ['public/v/**/*']

# REQUEST HEADERS
# ---------------------------
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
