[build]
  publish = "public"

  [build.environment]
    NPM_FLAGS = "--prefix=/dev/null"


# REQUEST HEADERS
# ---------------------------
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
