import { readFile } from 'fs/promises';
import { join, relative } from 'path';
import { plain, highlight } from 'cli-highlight';
import t from 'chalk';

var H=Object.defineProperty;var B=(e,s)=>{for(var i in s)H(e,i,{get:s[i],enumerable:!0});};var F={};B(F,{dev:()=>U,forRule:()=>k,forSample:()=>G,getSample:()=>N});var C={keyword:t.cyanBright,built_in:t.cyanBright,type:t.cyan.dim,literal:t.hex("#ef3b7d"),number:t.green,regexp:t.red,string:t.yellowBright,subst:t.white,symbol:t.white,class:t.white,function:t.cyanBright,title:t.white,params:t.white,comment:t.gray,doctag:t.green,meta:t.white,"meta-keyword":t.white,"meta-string":t.white,section:t.white,tag:t.hex("#BECAFF"),name:e=>/(end)?comment/.test(e)?t.gray(e):t.hex("#FF93BC")(e),"builtin-name":t.white,attr:t.hex("#91EBC2"),attribute:t.white,variable:t.white,bullet:t.white,code:t.white,emphasis:t.italic,strong:t.bold,formula:t.white,link:t.underline,quote:t.white,"selector-tag":t.white,"selector-id":t.white,"selector-class":t.white,"selector-attr":t.white,"selector-pseudo":t.white,"template-tag":t.white,"template-variable":t.white,addition:t.green,deletion:t.red,default:plain};function f(e){return e.replace(/(\x9B|\x1B\[)[0-?]*[ -\\/]*[@-~]/g,"")}function A(e){return t.gray(f(e))}function v(e){return /{[{%]-?|-?[%}]}/.test(e)?e:t.yellowBright(f(e))}function D(e){return f(e).replace(/-?\s*[a-zA-Z._]+/g,z).replace(/[|,.:]/g,s=>t.hex("#e75378")(f(s))).replace(/(?:=|[!=]=|[<>]=?|(?:and|or|contains|with|in|null)\b)/g,_).replace(/["'][\s\S]*?["']/g,v)}function W(e){return /\./.test(e)?e.replace(/[a-zA-Z_.]*\.?/g,s=>t.white(s)):/break|continue|else/.test(e)?t.hex("#ef3b7d")(e):t.white(e)}function L(e){return f(e).replace(/[a-zA-Z_]+\b[:]?/g,q).replace(/[|,.:]/g,s=>t.hex("#e75378")(f(s))).replace(/["'][\s\S]*?["']/g,v)}function _(e){return /null|false|nil|true/.test(e)?t.hex("#FF91E3")(e):t.hex("#cb3f6e")(f(e))}function q(e){return /:$/.test(e)?t.hex("#7ef0ff")(e):/\./.test(e)?W(e):t.white(e)}function z(e){return /comment|endcomment/.test(e)?t.gray(f(e)):t.hex("#ef3b7d")(e)}function m(e,s={}){Object.assign(s,{theme:C,language:"html"});let i=highlight(e,s);return s.language!=="html"?i:i.replace(/(?<={%-?)[\s\S]*?(?=-?%})/g,D).replace(/(?<={{)[\s\S]*?(?=}})/g,L).replace(/{{-|{%-|{{|{%|}}|%}|-}}|-%}/g,A)}var O=(e,s)=>{let i=function(n){return [e,"```js",JSON.stringify(n,null,2),"```"].join(`
`)};return s?i.description=[e,"```js",JSON.stringify(s,null,2),"```"].join(`
`):i.description=e,i},N=async e=>{let[s,i,r]=e.split("/"),n=join(process.cwd(),"tests",s,"samples",i,r.endsWith(".txt")?r:r+".txt"),o=await readFile(n);if(!o)throw new Error("Sample file could not be located in: "+n);return o.toString()},U=e=>async(s,i)=>{let r=typeof s=="string"?join(process.cwd(),"tests",s):join(process.cwd(),"tests","dev.txt"),n=await readFile(r);if(!n)throw new Error("Sample file could not be located in: "+r);let o=relative(process.cwd(),r),a=n.toString();if(e.log(t.blueBright(o)),typeof i=="function")i(a,m),e.pass();else if(typeof s=="function")s(a,m),e.pass();else throw TypeError("Missing callback type")},k=(e,s)=>async(i,r)=>{if(Array.isArray(i)){let[n,o,a]=e.split("/"),p=join(process.cwd(),"tests",n,"samples",o,a.endsWith(".txt")?a:a+".txt");for(let g=0;g<i.length;g++){let c=i[g],w=await readFile(p);if(!w)throw new Error("Sample file could not be located in: "+p);let l=w.toString();if(!l.trimStart().startsWith("---"))throw new Error("Missing description in sample file!");let h=l.indexOf("---",3);if(h<0)throw new Error("Missing closing description dashes, eg: ---");let S=`### Snapshot ${g+1}
`+l.slice(3,h).trim(),d=l.slice(h+3).trimStart();if(typeof c=="object"){let u=typeof s=="object"?{[s.lexer]:{...c}}:c;r.call({highlight(b,y){return m(b,y)}},d,u,O(S,u));}else r.call({highlight(u,b){return m(u,b)}},d,c,O(S));}}else {let n=Object.entries(i),[o,a]=e.split("/");for(let[p,g]of n){let c=join(process.cwd(),"tests",o,"samples",a,p.endsWith(".txt")?p:p+".txt"),w=await readFile(c);if(!w)throw new Error("Sample file could not be located in: "+c);let l=w.toString();if(!l.trimStart().startsWith("---"))throw new Error("Missing description in sample file!");let h=l.indexOf("---",3);if(h<0)throw new Error("Missing closing description dashes, eg: ---");let S=l.slice(h+3).trimStart();for(let d=0;d<g.length;d++){let u=g[d],b=`### Snapshot ${d+1}
`+l.slice(3,h).trim();if(typeof u=="object"){let y=typeof s=="object"?{[s.lexer]:{...u}}:u;r.call({highlight(E,T){return m(E,T)}},S,y,O(b,y));}else r.call({highlight(y,E){return m(y,E)}},S,u,O(b));}}}},G=e=>async(s,i)=>{let[r,n]=e.split("/");for(let o=0;o<s.length;o++){let a=s[o],p=join(process.cwd(),"tests",r,"samples",n,a.endsWith(".txt")?a:a+".txt"),g=await readFile(p);if(!g)throw new Error("Sample file could not be located in: "+p);let c=g.toString();if(!c.trimStart().startsWith("---"))throw new Error("Missing description in sample file!");let l=c.indexOf("---",3);if(l<0)throw new Error("Missing closing description dashes, eg: ---");let $=c.slice(l+3).trimStart(),h=`### Snapshot ${o+1}
`+c.slice(3,l).trim();i($,O(h));}};

export { F as default };
